# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.12
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    -   id: black
        name: black (python) Formatting
-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
    -   id: pydocstyle
        args:
        - --convention=google
        - --add-select=D204
        - --add-ignore=D100,D101,D102,D104,D105,D106,D107
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        name: isort (python) Import Sorting
        args:
        - --settings-file .isort.cfg
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.7.4'
    hooks:
    -   id: ruff
        args: [--select, "RUF"]
